version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      # Connecting to the mongodb service defined below
      - MONGO_URI=mongodb://mongodb:27017/analytics-dashboard
      - REDIS_URI=redis://redis:6379
      - CLIENT_URL=http://localhost
      - JWT_SECRET=super_secret_jwt_key_for_dev_only
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
